### PR TITLE
Upgrade `autoneg-controller` to an upstream release

### PR DESCRIPTION
**Pull request by JanCVanB**
We used (and built) the existing fork/branch to get a bug fix,
but Google's upstream repo has since fixed the bug and published releases.

### CODE REVIEW

**Comment by JanCVanB** [comment]
Is `setup/scripts/fix_autoneg.sh` related to the `retry-register-with-backend` problem? If so, should we also update/remove it (and its references in `cloudbuild.yaml` and `README.md`)?

**Comment by danisla** [comment]
@JanCVanB can you reconcile the changed in the manifest too?
https://github.com/GoogleCloudPlatform/gke-autoneg-controller/blob/master/deploy/autoneg.yaml

**Comment by JanCVanB** [comment]
> @JanCVanB can you reconcile the changed in the manifest too? https://github.com/GoogleCloudPlatform/gke-autoneg-controller/blob/master/deploy/autoneg.yaml

Is https://github.com/selkies-project/selkies/pull/48/commits/bfc2076d4e5be2abdb5907fb463e32869cfaf587 what you had in mind?

**Comment by danisla** [comment]
> > @JanCVanB can you reconcile the changed in the manifest too? https://github.com/GoogleCloudPlatform/gke-autoneg-controller/blob/master/deploy/autoneg.yaml
> 
> Is [bfc2076](https://github.com/selkies-project/selkies/commit/bfc2076d4e5be2abdb5907fb463e32869cfaf587) what you had in mind?

Not really, need to diff the upstream manifest with the current one.

**Comment by JanCVanB** [comment]
> > > @JanCVanB can you reconcile the changed in the manifest too? https://github.com/GoogleCloudPlatform/gke-autoneg-controller/blob/master/deploy/autoneg.yaml
> > 
> > 
> > Is [bfc2076](https://github.com/selkies-project/selkies/commit/bfc2076d4e5be2abdb5907fb463e32869cfaf587) what you had in mind?
> 
> Not really, need to diff the upstream manifest with the current one.

Ah, the entire file, not just the changed subsection - on it

**Comment by JanCVanB** [comment]
> @JanCVanB can you reconcile the changed in the manifest too? https://github.com/GoogleCloudPlatform/gke-autoneg-controller/blob/master/deploy/autoneg.yaml

@danisla how about this: https://github.com/selkies-project/selkies/pull/48/commits/18d013e55b69446171954ae82ac1fb22358c2db7

**Comment by JanCVanB** [comment]
@danisla Thanks for those (now-overwritten, whoops) comments, they made perfect sense. How does https://github.com/selkies-project/selkies/pull/48/commits/d7a520d1796e014d4a2402f9dbeb605fc1f460df look?

**Comment by JanCVanB** [comment]
Closing for staleness

**Pull request closed without merging**
